language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 5.6.13

before_install:
  - composer selfupdate

install:
  - composer install

script:
   - bin/phpspec run --format=pretty
   - bin/phpunit --testdox
   - bin/behat --format=pretty