language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'

install:
  - composer install ${COMPOSER_FLAGS}

script:
   - bin/phpspec run --format=pretty
   - bin/phpunit --testdox
   - if [[ ${TRAVIS_PHP_VERSION:0:3} -ne "8.0" ]]; then bin/behat --format=pretty; fi;
   - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then bin/behat --format=pretty --suite=core; fi
